/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_learn_1047038_8_compiled.h"
#include "tflite-model/tflite_anomaly_1047038_9_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1047038_1[] = { "Idle", "Push-Left", "Push-Right", "Swipe" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1047038_7_axes[] = { 0, 1 };
const uint32_t ei_dsp_config_1047038_7_axes_size = 2;
ei_dsp_config_raw_t ei_dsp_config_1047038_7 = {
    7, // uint32_t blockId
    1, // int implementationVersion
    2, // int length of axes
    1.0f // float scale-axes
};

const float ei_dn_standard_scaler_mean_1047038_7[18] = { 92.3964265773311, 95.93690675600223, 88.70407593523171, 94.499720826354, 84.26856504745952, 91.96259073143496, 80.24734785036293, 88.20212171970967, 77.28699050809604, 83.0999441652708, 75.52428810720268, 78.33668341708542, 73.91457286432161, 74.91624790619765, 71.58012283640424, 74.58849804578448, 69.95030709101061, 75.42769402568398 };
const float ei_dn_standard_scaler_scale_1047038_7[18] = { 0.047180729424672704, 0.06679900579545014, 0.03812926649063115, 0.05476483732097856, 0.03249434223968196, 0.043868341974657665, 0.029467785900916102, 0.03582338006671131, 0.0279256547672414, 0.030191303537797476, 0.027174289195647988, 0.0272065288007586, 0.026494535536003675, 0.025672406301462843, 0.025548395647504846, 0.02531860323695446, 0.024813378032898237, 0.025375784224648076 };
const float ei_dn_standard_scaler_var_1047038_7[18] = { 449.23201403132464, 224.1093637428378, 687.8331436324269, 333.4236459298845, 947.0752765003787, 519.6339997649371, 1151.6088357913347, 779.2321786362215, 1282.3107129418427, 1097.0748799522207, 1354.2025089153171, 1350.9949636513127, 1424.5817585975635, 1517.2838845259316, 1532.0492754734585, 1559.9853283415737, 1624.1577762876034, 1552.9628064636186 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1047038_7 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1047038_7,
    .mean_data_len = 18,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1047038_7,
    .scale_data_len = 18,
    .var_data = (float *)ei_dn_standard_scaler_var_1047038_7,
    .var_data_len = 18
};
ei_data_normalization_t ei_data_normalization_config_1047038_7 = {
    (void *) &ei_data_normalization_standard_scaler_config_1047038_7, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1047038_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1047038_1[ei_dsp_blocks_1047038_1_size] = {
    { // DSP block 7
        7,
        18, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_1047038_7, // pointer to config struct
        ei_dsp_config_1047038_7_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1047038_7_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1047038_7, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1047038_8 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1047038_8_init,
    .model_invoke = &tflite_learn_1047038_8_invoke,
    .model_reset = &tflite_learn_1047038_8_reset,
    .model_input = &tflite_learn_1047038_8_input,
    .model_output = &tflite_learn_1047038_8_output,
};

const ei_config_tflite_eon_graph_t ei_config_graph_1047038_9 = {
    .implementation_version = 1,
    .model_init = &tflite_anomaly_1047038_9_init,
    .model_invoke = &tflite_anomaly_1047038_9_invoke,
    .model_reset = &tflite_anomaly_1047038_9_reset,
    .model_input = &tflite_anomaly_1047038_9_input,
    .model_output = &tflite_anomaly_1047038_9_output,
};

const uint8_t ei_output_tensors_indices_1047038_8[1] = { 0 };
const uint8_t ei_output_tensors_size_1047038_8 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1047038_8 = {
    .implementation_version = 1,
    .block_id = 8,
    .output_tensors_indices = ei_output_tensors_indices_1047038_8,
    .output_tensors_size = ei_output_tensors_size_1047038_8,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1047038_8,
    .dequantize_output = 0,
};

ei_learning_block_config_anomaly_gmm_t ei_learning_block_config_1047038_9 = {
    .implementation_version = 1,
    .block_id = 9,
    .anom_axis = ei_classifier_anom_axes_1047038_9,
    .anom_axes_size = 4,
    .graph_config = (void*)&ei_config_graph_1047038_9
};

const uint8_t ei_learning_blocks_1047038_1_size = 2;
const uint32_t ei_learning_block_1047038_8_inputs[1] = { 7 };
const uint8_t ei_learning_block_1047038_8_inputs_size = 1;
const uint32_t ei_learning_block_1047038_9_inputs[1] = { 7 };
const uint8_t ei_learning_block_1047038_9_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1047038_1[ei_learning_blocks_1047038_1_size] = {
    {
        8,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1047038_8,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1047038_8_inputs,
        ei_learning_block_1047038_8_inputs_size,
    },
    {
        9,
        &run_gmm_anomaly,
        (void*)&ei_learning_block_config_1047038_9,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1047038_9_inputs,
        ei_learning_block_1047038_9_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1047038_8 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1047038_1_size = 2;
const ei_postprocessing_block_t ei_postprocessing_blocks_1047038_1[ei_postprocessing_blocks_1047038_1_size] = {
    {
        .block_id = 8,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1047038_8,
        .input_block_id = 8
    },
    {
        .block_id = 9,
        .type = EI_CLASSIFIER_MODE_ANOMALY_GMM,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_anomaly,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 9
    },
};

const uint8_t freeform_outputs_1047038_1_size = 0;

uint32_t *freeform_outputs_1047038_1 = nullptr;

const ei_impulse_t impulse_1047038_1 = {
    .project_id = 1047038,
    .project_owner = "Abhi_21",
    .project_name = "Ultrasonic Sensor Gesture Recognition",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 5,

    .nn_input_frame_size = 18,
    .raw_sample_count = 9,
    .raw_samples_per_frame = 2,
    .dsp_input_frame_size = 9 * 2,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 100,
    .frequency = 10,

    .dsp_blocks_size = ei_dsp_blocks_1047038_1_size,
    .dsp_blocks = ei_dsp_blocks_1047038_1,

    .learning_blocks_size = ei_learning_blocks_1047038_1_size,
    .learning_blocks = ei_learning_blocks_1047038_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1047038_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1047038_1,

    .output_tensors_size = 2,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "distleft + distright",
    .slice_size = (9/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_GMM,
    .label_count = 4,
    .categories = ei_classifier_inferencing_categories_1047038_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1047038_1_size,
    .freeform_outputs = freeform_outputs_1047038_1
};

ei_impulse_handle_t impulse_handle_1047038_1 = ei_impulse_handle_t( &impulse_1047038_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1047038_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1047038_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1047038_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1047038_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
